version: "3.9"

services:

  database:
    build:
      network: host
      dockerfile: extra/Dockerfile.database
    image: nathants/webapp-vanilla:database${suffix:-}
    ports: ["27017"]

  backend:
    build:
      network: host
      dockerfile: extra/Dockerfile.backend
    image: nathants/webapp-vanilla:backend${suffix:-}
    ports: ["8080"]
    links: ["database"]

  frontend:
    build:
      network: host
      dockerfile: extra/Dockerfile.frontend
    image: nathants/webapp-vanilla:frontend${suffix:-}
    ports: ["8000"]

  test:
    build:
      network: host
      dockerfile: extra/Dockerfile.test
    image: nathants/webapp-vanilla:test
    links: ["frontend", "backend"]
