version: "3.9"

services:

  database:
    build:
      network: host
      dockerfile: Dockerfile.database
    image: ${registry}/webapp-vanilla:database${suffix:-}
    ports: ["27017"]

  backend:
    build:
      network: host
      dockerfile: Dockerfile.backend
    image: ${registry}/webapp-vanilla:backend${suffix:-}
    ports: ["8080"]
    links: ["database"]

  frontend:
    build:
      network: host
      dockerfile: Dockerfile.frontend
    image: ${registry}/webapp-vanilla:frontend${suffix:-}
    ports: ["8000"]

  test:
    build:
      network: host
      dockerfile: Dockerfile.test
    image: ${registry}/webapp-vanilla:test${suffix:-}
    links: ["frontend", "backend"]
